# Generated by Django 5.2.5 on 2025-09-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.FileField(blank=True, default='https://www.dreamstime.com/illustration/placeholder-profile.html', null=True, upload_to='profiles/'),
        ),
    ]
