# Generated by Django 5.2.5 on 2025-09-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='https://img.freepik.com/premium-vector/avatar-profile-picture-icon-gray-background-flat-design-style-resources-graphic-element-design_991720-445.jpg?semt=ais_incoming&w=740&q=80', max_length=300, null=True, upload_to='profile_images/'),
        ),
    ]
