# Generated by Django 5.2.3 on 2025-09-15 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_manager_id'),
        ('room', '0003_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hotel_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.hotel'),
            preserve_default=False,
        ),
    ]
