# Generated by Django 5.2.3 on 2025-09-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'hotel',
                'verbose_name_plural': 'hotels',
                'db_table': 'hotel_table',
                'ordering': ['-id'],
            },
        ),
    ]
