# Generated by Django 5.2.3 on 2025-09-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_add_hotel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='manager_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
